# action.yml
name: "PSONO Secret Whisperer"
description: "A GitHub Action for securely retrieving secrets from PSONO server"
author: "J.F.Heinrich"
branding:
  icon: "lock"
  color: "blue"

inputs:
  ci_api_key_id: # id of input
    description: "PSONO API key"
    required: true
  ci_api_secret_key_hex:
    description: "PSONO API secret key"
    required: true
  secret_id:
    description: "Secret ID to fetch"
    required: true
  ci_server_url:
    description: "The URL of the PSONO server, default: https://www.psono.pw/server"
    default: "https://www.psono.pw/server"
  secret_type:
    description: "Type of secret tp fetch: env or secret, default: secret"
    default: "secret"
  secret_fields:
    description: "Comma-separated list of secret keys to retrieve, default: username,password"
    default: "username,password"
  mask_secrets:
    description: "Comma-separated list of secret keys to be masked"

outputs:
  secrets:
    description: "Each secret is available as an individual output"

runs:
  using: "docker"
  image: "Dockerfile"
