name: Create new release
permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: 'Release ${{ github.ref_name }}'
          body: ${{ steps.changelog.outputs.changes }}

      - name: Create Pull Request for CHANGELOG.md
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          branch: changelog-update-${{ github.ref_name }}
          title: 'Update CHANGELOG.md for ${{ github.ref_name }}'
          body: 'Automated update of CHANGELOG.md by workflow.'
          base: main
          add-paths: CHANGELOG.md
